#! /bin/bash

echo "------------------------------------------------"
echo "Welcome to Lame converter script by Bass Jansson"
echo "------------------------------------------------"
echo

if [ $# -lt 3 ];
then
echo "Please give the directory which to convert,
the extension which to convert from,
and the extension which to convert to.
Program exited."
echo
exit
fi

FOLDER=$1
EXTFROM=$2
EXTTO=$3

if [ ! -d $FOLDER ]
then
echo "Directory doesn't exist, please give an existing directory.
Program exited."
echo
exit
fi

if [ $EXTTO != "mp3" ] && [ $EXTTO != "wav" ] && [ $EXTTO != "aif" ]
then
echo "No valid extension which to convert to. Use mp3, wav or aif.
Program exited."
echo
exit
fi

FILECOUNT=`ls -1 ${FOLDER}/*.${EXTFROM} 2> /dev/null | wc -l`
if [ $FILECOUNT -lt 1 ]
then
echo "No files in directory $FOLDER with extension ${EXTFROM}.
Program exited."
echo
exit
else
basename `ls -1 ${FOLDER}/*.${EXTFROM}`
echo
fi

echo "Are you sure you want to convert all of these files? (y/anything)"
read ANSWER

if [ $ANSWER != "y" ]
then
echo "Program exited."
echo
exit
fi

if [ ! -d ${FOLDER}/converted ]
then
mkdir ${FOLDER}/converted
fi

CFOLDER=${FOLDER}/converted

echo
echo "Started converting..."
echo

for f in ${FOLDER}/*.${EXTFROM};
do
echo "Converting: `basename $f`"
if [ $EXTTO == "mp3" ]
then
lame -V2 $f ${CFOLDER}/`basename $f ${EXTFROM}`${EXTTO} 2> /dev/null
else
if [ $EXTTO == "wav" || $EXTTO == "aif" ]
then
lame --decode $f ${CFOLDER}/`basename $f ${EXTFROM}`${EXTTO} 2> /dev/null
else
echo "Something went wrong, `basename $f` is not converted"
fi
fi
done

echo
echo "Done converting, see the converted folder for your new files."
echo
