#! /bin/bash

make

echo ""

PieterFilter "input" > input
PieterFilter "output" > output
PieterFilter "response" > response

echo "Generated data files 'input', 'output' and 'response'."
echo ""

gnuplot signal
gnuplot spectrum

echo "PNG files created with gnuplot."
echo ""
